# Stage 1: Build React app
FROM node:20-alpine as build

WORKDIR /app

# Copy package.json & lock first for caching
COPY package*.json ./
RUN npm install

# Copy all files and build
COPY . .
RUN npm run build

# Stage 2: Serve with nginx
FROM nginx:stable-alpine

# Copy build files to nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expose frontend port
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
